spring.application.name=gymapp-backend


# Si existe la variable SPRING_DATASOURCE_URL (en la nube), usa esa.
# Si no existe (en tu PC), usa localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gymapp}
# Lo mismo para usuario y contrasenia
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# 2. Configuracion de JPA / Hibernate (El "Traductor")
# 'update': Si cambias algo en el codigo Java (ej: agregas un campo), actualiza la tabla sin borrar los datos viejos.
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar SQL en consola (Vital para aprender)
# Esto te permitira ver las sentencias SQL que Spring genera por ti automaticamente.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Dialecto de MySQL (Opcional en versiones nuevas, pero buena practica)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



# CONFIGURACION JWT
# Clave secreta: Debe ser larga y compleja (para HMAC-SHA256)
# En produccion esto deberia ser una variable de entorno, no texto plano.
jwt.secret=UnaClaveMuySecretaYLoSuficientementeLargaParaQueSeaSegura12345
# Expiracion: 86400000 milisegundos = 24 horas
jwt.expiration=86400000