spring.application.name=gymapp-backend


# 1. Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gymapp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# 2. Configuración de JPA / Hibernate (El "Traductor")
# 'update': Si cambias algo en el código Java (ej: agregas un campo), actualiza la tabla sin borrar los datos viejos.
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar SQL en consola (Vital para aprender)
# Esto te permitirá ver las sentencias SQL que Spring genera por ti automáticamente.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Dialecto de MySQL (Opcional en versiones nuevas, pero buena práctica)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



# CONFIGURACIÓN JWT
# Clave secreta: Debe ser larga y compleja (para HMAC-SHA256)
# En producción esto debería ser una variable de entorno, no texto plano.
jwt.secret=UnaClaveMuySecretaYLoSuficientementeLargaParaQueSeaSegura12345
# Expiración: 86400000 milisegundos = 24 horas
jwt.expiration=86400000